rate_limit:
  delay: 1.0
  variant_delay: 2.0
  max_retries: 3
  backoff_factor: 2

output:
  format: json
  pretty_print: true
  date_format: iso
  fields:
    - prices
    - details
    - variants
  file_age: 86400  # Maximum age of cached files in seconds (default: 24 hours)

scraper:
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124'
  timeout: 10
  validate_ssl: true 