export interface ProductViewItem {
  product_id: number;
  product_title: string;
  product_variant: string | null;
  release_year: number | null;
  is_product_active: boolean;
  product_notes: string | null;
  product_created_at: string;
  product_updated_at: string;
  product_group_name: string | null;
  product_type_name: string;
  rating_name: string | null;
  region_name: string | null;
  price_usd: number | null;
  price_nok: number | null;
  price_nok_fixed: number | null;
  price_new_usd: number | null;
  price_new_nok: number | null;
  price_new_nok_fixed: number | null;
  final_price: number | null;
  normal_count: number;
  for_sale_count: number;
  collection_count: number;
  sold_count: number;
  total_count: number;
  total_sales: number;
  unique_buyers: number;
  avg_sale_price: number | null;
  max_sale_price: number | null;
  min_sale_price: number | null;
  pricecharting_id: string | null;
} 